version: "3"

services:
  postgres:
    image: postgres:14
    ports:
      - $POSTGRES_PORT:5432
    environment:
      POSTGRES_USER: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - $PGADMIN_PORT:80
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_DEFAULT_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_DEFAULT_PASSWORD
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    
  api:
    build: 
      context: ../Server/api
      dockerfile: Dockerfile
    ports:
      - $API_PORT:$API_PORT
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_PORT: $POSTGRES_PORT
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      API_PORT: $API_PORT
      TOKEN_SECRET: $TOKEN_SECRET
  
  mqtt:
    build: 
      context: ../Server/mqtt
      dockerfile: Dockerfile
    depends_on:
      - postgres

  portainer:
    image: portainer/portainer-ce
    container_name: portainer_container
    restart: always
    ports:
      - $PORTAINER_PORT:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  front:
    build:
      context: ../Frontend
      dockerfile: Dockerfile
    ports:
      - $FRONT_PORT:$FRONT_PORT
    depends_on:
      - api

volumes:
  portainer_data:
  postgres-data:
  pgadmin-data:
